### ISSUE TITLE
Compiz (Application Switcher) causing X to freeze

### ISSUE THREAD

**Issue by caringi** [compiz-reloaded/compiz#103]
Hi folks,

I am not sure if here is the right place to report this bug, but anyway... I'm using an updated Fedora 27 (compiz-0.8.14-3.fc27.x86_64) and I'm facing some freezes in Compiz when I try to switch to another window using ALT+TAB  (causing the entire session to freeze).

My videocard:

    00:02.0 VGA compatible controller: Intel Corporation Skylake GT2 [HD Graphics 520] (rev 07)

lsmod | grep "kms\|drm":

    drm_kms_helper        167936  1 i915
    drm                   372736  7 i915,drm_kms_helper

glxinfo data:

    name of display: :0
    display: :0  screen: 0
    direct rendering: Yes
    server glx vendor string: SGI
    server glx version string: 1.4
    Extended renderer info (GLX_MESA_query_renderer):
        Vendor: Intel Open Source Technology Center (0x8086)
        Device: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2)  (0x1916)
        Version: 17.2.4
        Accelerated: yes
        Video memory: 3072MB
        Unified memory: yes
        Preferred profile: core (0x1)
        Max core profile version: 4.5
        Max compat profile version: 3.0
        Max GLES1 profile version: 1.1
        Max GLES[23] profile version: 3.2

Follows a stacktrace:

    #0  0x00007f9809e60b89 in syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
    #1  0x00007f980792ab6a in sys_futex (val3=0, addr2=0x0, timeout=0x0, val1=-1, op=0, addr1=0x7f980ca21000) at xshmfence_futex.h:57
    #2  0x00007f980792ab6a in futex_wait (value=-1, addr=0x7f980ca21000) at xshmfence_futex.h:65
    #3  0x00007f980792ab6a in xshmfence_await (f=0x7f980ca21000) at xshmfence_futex.c:63
    #4  0x00007f98085c3ecd in loader_dri3_get_buffers () at /lib64/libGLX_mesa.so.0
    #5  0x00007f9806344c2e in intel_update_renderbuffers () at /usr/lib64/dri/i965_dri.so
    #6  0x00007f9806373970 in intelSetTexBuffer2 () at /usr/lib64/dri/i965_dri.so
    #7  0x0000560403cf848e in enableTexture (screen=screen@entry=0x560404226310, texture=texture@entry=0x560405dee060, filter=filter@entry=COMP_TEXTURE_FILTER_FAST) at texture.c:423
    #8  0x0000560403d13149 in enableFragmentOperationsAndDrawGeometry (mask=<optimized out>, filter=0, attrib=0x7ffeda12f5f0, texture=0x560405dee060, w=0x560405d57eb0) at paint.c:1115
    #9  0x0000560403d13149 in drawWindowTexture (w=0x560405d57eb0, texture=0x560405dee060, attrib=0x7ffeda12f5f0, mask=<optimized out>) at paint.c:1183
    #10 0x00007f97f9862773 in expoDrawWindowTexture () at /usr/lib64/compiz/libexpo.so
    #11 0x00007f97fc280251 in decorDrawWindow (w=0x560405d57eb0, transform=<optimized out>, attrib=0x7ffeda12f5f0, region=0x560403f295a0 <infiniteRegion>, mask=589824) at decoration.c:239
    #12 0x00007f97fb2460c0 in wallpaperDrawWindow () at /usr/lib64/compiz/libwallpaper.so
    #13 0x00007f97fb03fdec in loginoutDrawWindow () at /usr/lib64/compiz/libloginout.so
    #14 0x00007f97fac2e804 in obsDrawWindow (w=<optimized out>, transform=<optimized out>, attrib=<optimized out>, region=<optimized out>, mask=<optimized out>) at obs.c:285
    #15 0x00007f97f9860ee3 in expoDrawWindow () at /usr/lib64/compiz/libexpo.so
    #16 0x0000560403d139c9 in paintWindow (w=0x560405d57eb0, attrib=<optimized out>, transform=0x7ffeda130250, region=0x560403f295a0 <infiniteRegion>, mask=65536) at paint.c:1267
    #17 0x00007f980066da86 in smartputPaintWindow () at /usr/lib64/compiz/libsmartput.so
    #18 0x00007f97ff846101 in minPaintWindow (w=0x560405d57eb0, attrib=<optimized out>, transform=<optimized out>, region=0x560403f295a0 <infiniteRegion>, mask=0) at minimize.c:536
    #19 0x00007f97fdd30d57 in shiftPaintWindow () at /usr/lib64/compiz/libshift.so
    #20 0x00007f97fc4891b1 in splashPaintWindow () at /usr/lib64/compiz/libsplash.so
    #21 0x00007f97fbe757e4 in resizePaintWindow (w=0x560405d57eb0, attrib=<optimized out>, transform=<optimized out>, region=<optimized out>, mask=0) at resize.c:1469
    #22 0x00007f97fba6be96 in widgetPaintWindow () at /usr/lib64/compiz/libwidget.so
    #23 0x00007f97fb85f5f3 in putPaintWindow () at /usr/lib64/compiz/libput.so
    #24 0x00007f97fb6560d8 in fadePaintWindow (w=0x560405d57eb0, attrib=<optimized out>, transform=0x7ffeda130250, region=<optimized out>, mask=<optimized out>) at fade.c:416
    #25 0x00007f97fb03fd4d in loginoutPaintWindow () at /usr/lib64/compiz/libloginout.so
    #26 0x00007f97fae35f94 in thumbPaintWindow () at /usr/lib64/compiz/libthumbnail.so
    #27 0x00007f97fac2e762 in obsPaintWindow (w=<optimized out>, attrib=<optimized out>, transform=<optimized out>, region=<optimized out>, mask=<optimized out>) at obs.c:225
    #28 0x00007f97faa29997 in movePaintWindow (w=<optimized out>, attrib=<optimized out>, transform=<optimized out>, region=<optimized out>, mask=<optimized out>) at move.c:871
    #29 0x00007f97fa820fbe in cubePaintWindow (w=<optimized out>, attrib=<optimized out>, transform=<optimized out>, region=<optimized out>, mask=<optimized out>) at cube.c:1613
    #30 0x00007f97fa618303 in scalePaintWindow (w=0x560405d57eb0, attrib=<optimized out>, transform=0x7ffeda130250, region=0x560403f295a0 <infiniteRegion>, mask=0) at scale.c:422
    #31 0x00007f97fa207923 in switchPaintWindow (w=0x560405d57eb0, attrib=<optimized out>, transform=0x7ffeda130250, region=0x560403f295a0 <infiniteRegion>, mask=0) at switcher.c:1675
    #32 0x00007f97f9ffdbac in WindowWrapper::paintWindow(_WindowPaintAttrib const*, _CompTransform const*, _XRegion*, unsigned int) () at /usr/lib64/compiz/libscreensaver.so
    #33 0x00007f97f9860c96 in expoPaintWindow () at /usr/lib64/compiz/libexpo.so
    #34 0x00007f97fa2064bb in switchPaintOutput (s=0x560404226310, sAttrib=<optimized out>, transform=0x560403d1e0e0 <identity>, region=0x56040455fe30, output=<optimized out>, mask=70) at switcher.c:1408
    #35 0x00007f97f9ffdb09 in ScreenWrapper::paintOutput(_ScreenPaintAttrib const*, _CompTransform const*, _XRegion*, _CompOutput*, unsigned int) () at /usr/lib64/compiz/libscreensaver.so
    #36 0x00007f97f98603ed in expoPaintOutput () at /usr/lib64/compiz/libexpo.so
    #37 0x0000560403cfa19d in paintScreen (s=0x560404226310, outputs=<optimized out>, numOutput=<optimized out>, mask=<optimized out>) at display.c:1381
    #38 0x00007f980025ef15 in shotPaintScreen (s=0x560404226310, outputs=<optimized out>, numOutput=<optimized out>, mask=<optimized out>) at screenshot.c:303
    #39 0x00007f97ffe53823 in workaroundsPaintScreen () at /usr/lib64/compiz/libworkarounds.so
    #40 0x00007f97fdd2fc82 in shiftPaintScreen () at /usr/lib64/compiz/libshift.so
    #41 0x00007f97fa820d36 in cubePaintScreen (s=0x560404226310, outputs=0x56040455fde0, numOutputs=3, mask=4) at cube.c:818
    #42 0x00007f97f9ffdb49 in ScreenWrapper::paintScreen(_CompOutput*, int, unsigned int) () at /usr/lib64/compiz/libscreensaver.so
    #43 0x00007f97f9861bf7 in expoPaintScreen () at /usr/lib64/compiz/libexpo.so
    #44 0x0000560403cfa786 in eventLoop () at display.c:1626
    #45 0x0000560403cf65e7 in main (argc=5, argv=<optimized out>) at main.c:521

**Comment by soreau** [comment]
Sounds a lot like emerald-#31, does it happen when starting compiz with --loose-binding option?

**Comment by caringi** [comment]
@soreau first I tried to set "Loose Binding" option through fusion-icon and reload the WM and the problem persisted, but then restarted compiz via command-line using the "--loose-binding" option and it fixed the problem. Thanks.
