### ISSUE TITLE
Error: failed to load fragment program (VirtualBox)

### ISSUE THREAD

**Issue by hubslave** [compiz-reloaded/compiz#109]
When I'm enabling Color filter I see this error repeatedly in the console:
```
compiz (core) - Error: failed to load fragment program
```
Also Compiz crashes from time to time

**Comment by soreau** [comment]
Hi, does Color Filter work at all? This message could point to a driver problem. You can enable the Crash Handler plugin and try to get a backtrace for the crashes, which should end up in a file in /tmp/ after the crash.

**Comment by hubslave** [comment]
Yes, the Color Filter does work overall, it might be a problem only with some particular filters.
This is a sample output after Alt-Super-d and multiple Alt-Super-s strokes:

```
compiz (core) - Error: failed to load fragment program
compiz (colorfilter) - Info: Single filter mode (using blackandwhite filter)
compiz (colorfilter) - Info: Single filter mode (using blueish_filter filter)
compiz (colorfilter) - Info: Single filter mode (using colornegative filter)
compiz (core) - Error: failed to load fragment program
compiz (colorfilter) - Info: Single filter mode (using contrast filter)
compiz (colorfilter) - Info: Single filter mode (using deuteranopia filter)
compiz (colorfilter) - Info: Single filter mode (using grayscale filter)
```

It seems the crash is always triggered by Alt+Tab, here is the log:

```
Reading symbols from compiz...(no debugging symbols found)...done.
Attaching to program: /usr/bin/compiz, process 11862
[New LWP 11863]
[New LWP 11864]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x00007f2a1bb18867 in waitpid () from /usr/lib/libc.so.6
(gdb) 
Thread 3 (Thread 0x7f2a0ffeb700 (LWP 11864)):
#0  0x00007f2a1be193bd in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2a15d105d4 in  () at /usr/lib/dri/swrast_dri.so
#2  0x00007f2a15d10428 in  () at /usr/lib/dri/swrast_dri.so
#3  0x00007f2a1be1308c in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2a1bb4ae7f in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7f2a107ec700 (LWP 11863)):
#0  0x00007f2a1be193bd in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2a15d105d4 in  () at /usr/lib/dri/swrast_dri.so
#2  0x00007f2a15d10428 in  () at /usr/lib/dri/swrast_dri.so
#3  0x00007f2a1be1308c in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2a1bb4ae7f in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7f2a1e71ad80 (LWP 11862)):
#0  0x00007f2a1bb18867 in waitpid () at /usr/lib/libc.so.6
#1  0x00007f2a1ba96bcf in do_system () at /usr/lib/libc.so.6
#2  0x00007f2a048f572b in  () at /usr/lib/compiz/libcrashhandler.so
#3  0x00007f2a1ba898e0 in <signal handler called> () at /usr/lib/libc.so.6
#4  0x00007f2a1bbac651 in __memmove_avx_unaligned_erms () at /usr/lib/libc.so.6
#5  0x00007f2a1595fc1e in  () at /usr/lib/dri/swrast_dri.so
#6  0x00007f2a1595d94a in  () at /usr/lib/dri/swrast_dri.so
#7  0x000055ed47095dee in enableTexture ()
#8  0x000055ed470b0ac9 in drawWindowTexture ()
#9  0x00007f29ff98e5d1 in  () at /usr/lib/compiz/libcolorfilter.so
#10 0x00007f2a042e2261 in  () at /usr/lib/compiz/libdecoration.so
#11 0x000055ed470b1349 in paintWindow ()
#12 0x00007f2a044e9997 in  () at /usr/lib/compiz/libmove.so
#13 0x00007f2a040db7e4 in  () at /usr/lib/compiz/libresize.so
#14 0x00007f29ff37af8e in  () at /usr/lib/compiz/libcube.so
#15 0x00007f29ff173923 in  () at /usr/lib/compiz/libswitcher.so
#16 0x000055ed470aec72 in  ()
#17 0x000055ed470afa85 in paintOutput ()
#18 0x00007f2a040dc190 in  () at /usr/lib/compiz/libresize.so
#19 0x00007f29ff37ae0b in  () at /usr/lib/compiz/libcube.so
#20 0x00007f29ff172233 in  () at /usr/lib/compiz/libswitcher.so
#21 0x00007f29fef6911c in  () at /usr/lib/compiz/librotate.so
#22 0x000055ed47097afd in paintScreen ()
#23 0x00007f29ff37ad06 in  () at /usr/lib/compiz/libcube.so
#24 0x000055ed470980e6 in eventLoop ()
#25 0x000055ed4709431f in main ()


#0  0x00007f2a1bb18867 in waitpid () at /usr/lib/libc.so.6
#1  0x00007f2a1ba96bcf in do_system () at /usr/lib/libc.so.6
#2  0x00007f2a048f572b in  () at /usr/lib/compiz/libcrashhandler.so
#3  0x00007f2a1ba898e0 in <signal handler called> () at /usr/lib/libc.so.6
#4  0x00007f2a1bbac651 in __memmove_avx_unaligned_erms () at /usr/lib/libc.so.6
#5  0x00007f2a1595fc1e in  () at /usr/lib/dri/swrast_dri.so
#6  0x00007f2a1595d94a in  () at /usr/lib/dri/swrast_dri.so
#7  0x000055ed47095dee in enableTexture ()
#8  0x000055ed470b0ac9 in drawWindowTexture ()
#9  0x00007f29ff98e5d1 in  () at /usr/lib/compiz/libcolorfilter.so
#10 0x00007f2a042e2261 in  () at /usr/lib/compiz/libdecoration.so
#11 0x000055ed470b1349 in paintWindow ()
#12 0x00007f2a044e9997 in  () at /usr/lib/compiz/libmove.so
#13 0x00007f2a040db7e4 in  () at /usr/lib/compiz/libresize.so
#14 0x00007f29ff37af8e in  () at /usr/lib/compiz/libcube.so
#15 0x00007f29ff173923 in  () at /usr/lib/compiz/libswitcher.so
#16 0x000055ed470aec72 in  ()
#17 0x000055ed470afa85 in paintOutput ()
#18 0x00007f2a040dc190 in  () at /usr/lib/compiz/libresize.so
#19 0x00007f29ff37ae0b in  () at /usr/lib/compiz/libcube.so
#20 0x00007f29ff172233 in  () at /usr/lib/compiz/libswitcher.so
#21 0x00007f29fef6911c in  () at /usr/lib/compiz/librotate.so
#22 0x000055ed47097afd in paintScreen ()
#23 0x00007f29ff37ad06 in  () at /usr/lib/compiz/libcube.so
#24 0x000055ed470980e6 in eventLoop ()
#25 0x000055ed4709431f in main ()
A debugging session is active.

	Inferior 1 [process 11862] will be detached.

Quit anyway? (y or n) [answered Y; input not from terminal]
Detaching from program: /usr/bin/compiz, process 11862
```

**Comment by soreau** [comment]
Huh. I do see some frag prog failure messages here too but they seem to only happen on the first cycle of filters. Repeatedly switching filters, the messages stop happening. Not sure what's going on there.

The crash you are experiencing is apparently happening to several people with X 1.19.6 while 1.19.5 reportedly doesn't suffer from these crashes.

**Comment by hubslave** [comment]
I see. Hopefully the crash for X 1.19.6 can be fixed on compiz side.
Also it would be helpful to print more details on fragment program error (shader name?)
